### ISSUE TITLE
Error on Update Records

### ISSUE THREAD

**Issue by lifers5555** [DaniGTA/CloudFlare-DDNS-Updater#3]
Heya, v2.1.1, getting the following error on Update Records:
Cant find new IP |System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement)
   at CloudFlareDDNS.CloudFlareAPI.getExternalAddress()

Any advice?

**Comment by DaniGTA** [comment]
Will be fixed next patch
